import React, { useState } from 'react'
import { useDispatch } from 'react-redux'
import Head from 'next/head'
import TextareaAutosize from '@material-ui/core/TextareaAutosize'
import styles from '../../styles/CardCreate.module.css'
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles'
import TextField from '@material-ui/core/TextField'
import Button from '@material-ui/core/Button'
import { addBlog } from '../../store/actions/blogActions'

const New = () => {
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const dispatch = useDispatch()

  const createBlog = async (event: React.FormEvent) => {
    event.preventDefault()
    dispatch(
      addBlog({
        title: title,
        body: body,
      })
    )
    setTitle('')
    setBody('')
  }

  return (
    <div>
      <Head>
        <title>Add Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <React.Fragment>
        <form
          action=""
          method="POST"
          className={styles.container}
          onSubmit={createBlog}
          style={{ textAlign: 'center' }}
        >
          <TextField
            required
            id="standard-required"
            value={title}
            label="Title"
            onChange={(e) => setTitle(e.target.value)}
            style={{ width: '20%' }}
          />

          <TextareaAutosize
            value={body}
            aria-label="minimum height"
            onChange={(e) => setBody(e.target.value)}
            rowsMin={10}
            cols={30}
            placeholder="Write body"
            style={{ width: '20%' }}
          />
          <Button
            variant="contained"
            color="primary"
            type="submit"
            style={{ width: '20%' }}
          >
            Create Blog
          </Button>
        </form>
      </React.Fragment>
    </div>
  )
}

export default New
