import React, { FunctionComponent, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Head from 'next/head'

import Cards from '../components/Cards'
import styles from '../styles/Home.module.css'

import { fetchblogs } from '../store/actions/blogActions'

interface Props {
  data?: string[]
}

const Home = (props: Props) => {
  const dispatch = useDispatch()
  const blogState = useSelector((state) => state.blog)

  useEffect(() => {
    dispatch(fetchblogs())
  }, [])

  return (
    <main className={styles.container}>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cards data={blogState.blogs} />
    </main>
  )
}
export default Home
