import React, { FunctionComponent } from 'react'
import Head from 'next/head'

import Cards from '../components/Cards'
import styles from '../styles/Home.module.css'

interface Props {
  data?: string[]
}

const Home = (props: Props) => {
  return (
    <main className={styles.container}>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cards data={props.data} />
    </main>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://simple-blog-api.crew.red/posts`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default Home
